-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 13:46:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newsdb
-- -----------------------------------------------------
DROP Schema IF EXISTS `newsdb`;
CREATE SCHEMA IF NOT EXISTS `newsdb` DEFAULT CHARACTER SET utf8 ;
USE `newsdb` ;

-- -----------------------------------------------------
-- Table `newsdb`.`news_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsdb`.`news_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsdb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsdb`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `brief` VARCHAR(500) NOT NULL,
  `contentID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `_idx` (`contentID` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`contentID`)
    REFERENCES `newsdb`.`news_content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `news_content` (`id`,`content`) VALUES (1,'I was born on 10 July 1989 in Vitebsk.');
INSERT INTO `news_content` (`id`,`content`) VALUES (2,'My sister was  born on 5 November 1991 in Vitebsk.');
INSERT INTO `news_content` (`id`,`content`) VALUES (3,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO `news_content` (`id`,`content`) VALUES (4,'content4');
INSERT INTO `news_content` (`id`,`content`) VALUES (5,'content5');
INSERT INTO `news_content` (`id`,`content`) VALUES (6,'content6');
INSERT INTO `news_content` (`id`,`content`) VALUES (7,'content7');
INSERT INTO `news_content` (`id`,`content`) VALUES (8,'content8');
INSERT INTO `news_content` (`id`,`content`) VALUES (9,'content9');
INSERT INTO `news_content` (`id`,`content`) VALUES (10,'content10');
INSERT INTO `news_content` (`id`,`content`) VALUES (11,'content11');

INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (1,'1989-07-10','My Birthday','I was born',1);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (2,'1991-11-05','sister\'s birthday','My sister was born',2);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (3,'2017-08-25','Lorem ipsum','Lorem ipsum dolor sit amet',3);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (4,'2017-08-26','title4','brief4',4);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (5,'2017-08-27','title5','brief5',5);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (6,'2017-08-28','title6','brief6',6);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (7,'2017-08-29','title7','brief7',7);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (8,'2017-08-30','title8','brief8',8);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (9,'2017-08-31','title9','brief9',9);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (10,'2017-09-01','title10','brief10',10);
INSERT INTO `news` (`id`,`date`,`title`,`brief`,`contentID`) VALUES (11,'2017-09-01','title11','brief11',11);
